version: "3.9"

services: 
  twitter-db:
    image: postgres:14.1-alpine
    container_name: twitter-db
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes: 
      - postgres_volume:/var/lib/postgresql

volumes: 
  postgres_volume:
