version: "3.7"

services: 
  twitter-db:
      image: postgres
      container_name: twitter-db
      environment:
        POSTGRES_USER: ${DATABASE_USERNAME}
        POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
        POSTGRES_DB: ${DATABASE_NAME}
      ports:
        - "5432:5432"
      volumes: 
        - postgres_volume:/var/lib/postgresql

volumes: 
  postgres_volume: